name: Train transfer learning resnet18

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  train-model:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Configure WandB
      run: echo "WANDB_API_KEY=${{ secrets.WANDB_API_KEY }}" >> $GITHUB_ENV

    - name: Prepare dataset
      run: |
        ls -R ./dataset # Check dataset structure
        if [ ! -d ./dataset/train ]; then
          echo \"Dataset not found!\"
          exit 1
        fi

    - name: Run training
      env:
        WANDB_API_KEY: ${{ secrets.WANDB_API_KEY }}
      run: |
        pip install notebook
        jupyter nbconvert --to script cars-resnet18.ipynb
        python cars-resnet18.py

    - name: Save model artifacts
      if: success()
      uses: actions/upload-artifact@v3
      with:
        name: trained-model
        path: ./
